### ISSUE TITLE
omitting fields impl

### ISSUE THREAD

**Issue by dsilva** [davidpdrsn/juniper-from-schema#102]
Is it possible to omit the fields impl when the implementation would be a direct mapping from the struct?

For example, UserFields below seems like boilerplate:

```rust
pub struct User {
    pub id: String,
    pub name: String,
}

impl UserFields for User {
    fn field_id(&self, _: &Executor<Context>) -> FieldResult<&String> {
        Ok(&self.id)
    }
    fn field_name(&self, _: &Executor<Context>) -> FieldResult<&String> {
        Ok(&self.name)
    }
}
```

What's the best way to avoid writing that out for each field?

**Comment by davidpdrsn** [comment]
No that is not currently possible. I suggest you make a macro.

**Comment by davidpdrsn** [comment]
I have actually been hacking on a library with two macros designed to fix this. The code is still work in progress. You can find the code here https://github.com/davidpdrsn/juniper-from-schema-helpers
