### ISSUE TITLE
@juniper directive definition in schema

### ISSUE THREAD

**Issue by onelson** [davidpdrsn/juniper-from-schema#103]
Thanks for your work on this crate!

I haven't looked into the implementation to know how large a task this would be, but I thought it'd be good to offer the workflow I'm trying to implement as a use case for your crate.

The idea is to have a schema file on disk that can be used as the single source of truth for the data layout, shared between both the client and server. With this file, I'd aim to parse it with `juniper-from-schema` _and_ `apollo-tooling`'s `apollo codegen:generate` which produces Typescript definitions for symbols found in the schema.

Currently, the `@juniper` schema directive is used to communicate to the parser here (and only here, I think?) in `juniper-from-schema` to influence typing options for the traits generated.

Having this directive in your schema breaks editor and codegen tools that don't see definitions for the directive itself. Specifics: I'm using the IntelliJ graphql plugin, and apollo codegen. Both of these use the schema file to statically check the queries and types of the data being returned.

Both the editor plugin and codegen can be satisfied by adding something like the following to the head of the schema file:

```graphql
directive @juniper(
    ownership: String, # valid values: borrowed, owned, as_ref
    infallible: Boolean,
    with_time_zone: Boolean
) on FIELD_DEFINITION
```

Basically I stubbed out how the directive seems to be working if it were legit but did nothing. While this fixes the editor plugin and codegen, it breaks `juniper-from-schema` which panics saying it doesn't support directives.

So, where does this leave me and my desired workflow? Well, I can maintain two schema files, one for each use case (which would be super annoying), or I suppose I could try to ensure I don't need to use the directive for anything (might not be possible). I suppose another, less comfortable option might be build a `sed` step into the codegen process that spits out a version of the schema file without the directives in it, then set the editor and codegen to refer to this derivitive file. None of this is pretty.

So, with the problem known, a possible solution might be to not rely on directives but instead parse inline comments.

By moving the trait configuration info into comments, all parties should be able to consume the file without any issue.

So, instead of writing

```graphql
type Query {
    allMessages: [ChatLogEntry!]! @juniper(ownership: "owned")
}
```

I'd write:

```graphql
type Query {
    allMessages: [ChatLogEntry!]! # juniper: ownership="owned"
}
``` 

The comments could use the `juniper:` prefix with key/value pairs to follow. It shouldn't require sophisticated parser work to extract this data, but I'm not sure the comments are represented in the AST in a useful way so you can relate them to the field. That could be where the effort lies, but I'm not sure.

**Comment by onelson** [comment]
Working around this with `sed` for now. I'll use a schema file in the rust project to generate one in the frontend project:

https://github.com/onelson/e2e-rs/blob/d04e9dac6cdaa133608c28d6fb32a1b81b5422bf/web-frontend/package.json#L23

**Comment by davidpdrsn** [comment]
The GraphQL parser we use don't include comments in the AST. See https://github.com/graphql-rust/graphql-parser/issues/18. I also personally think using directives is the right way to go. It feels like they're designed specifically for cases like this.

I think a more elegant solution than `sed`ing would be nice 😊

I guess to solve this we have to support directive declarations for the `@juniper` directive, like the one you posted. I guess it would also make sense to fail the build if the declaration is not present. We could possible even write it to the schema on disk if it isn't present 🤔 

What do you think?

**Comment by onelson** [comment]
Sounds like a workable solution. Having the definition of the directive be legal across the board save me from having to wriggle to thread the needle.

I'd offer that it'd feel _a little rude_ to have this edit the schema file on disk automatically. That might cause issues in CI for some people.

I might prefer to have an error thrown and to include a good version of the directive definition in the output. I sort of clumsily wrote that without really knowing what I'm doing ;)

I bet you would be able to improve on it. For example, I'm not sure but in Typescript you can enumerate specific strings that are legal for a param. Maybe that's something graphql also knows how to express? Maybe not.

**Comment by davidpdrsn** [comment]
Yeah I like that idea 👍
