### ISSUE TITLE
Confguring the default ownership of fields

### ISSUE THREAD

**Issue by youssefhabri** [davidpdrsn/juniper-from-schema#112]
Is is possible to configure the default ownership of fields?
Right now the default is `borrowed` and to change that, I need to add `@juniper(ownership: "owned")` which is fine. But I was working on a side project and I found myself adding that to most fields, and only a few were left as `borrowed`. So it would be a nice thing to be able to set the default ownership.

I'm not sure if that's possible, but I thought I should ask.

Thanks :)

**Comment by davidpdrsn** [comment]
I would be open to adding a configuration for it. 

However I’m curious what your code looked like. Are you able to share it? I’m mostly curious about how you computed associations. Did you make database queries directly in all your “association” fields?

**Comment by youssefhabri** [comment]
This the side project I'm using this project in: https://github.com/youssefhabri/grevi-server

This is an example of what I'm doing:
```rust
fn field_author(
    &self,
    executor: &Executor<'_, Context>,
    _trail: &QueryTrail<'_, User, Walked>,
) -> FieldResult<User> {
    executor
        .context()
        .db()
        .user_by_id(self.author_id.clone())
        .map_err(|err| FieldError::from(err.to_string()))
}
```

**Comment by davidpdrsn** [comment]
Fields like that will lead to N+1 query bugs. Sameless plug: I actually created https://github.com/davidpdrsn/juniper-eager-loading to solve that problem. By using that you'd be able to return `&User`. You could also consider https://github.com/cksac/dataloader-rs even though that requires async.

I also gave your code a quick look and see lots of `.clone()`s which you can remove and return references instead (which should also be faster). You should be able to change resolvers like this:

```rust
fn field_name(&self, _: &Executor<'_, Context>) -> FieldResult<String> {
    Ok(self.username.clone())
}
```

to this

```rust
fn field_name(&self, _: &Executor<'_, Context>) -> FieldResult<&str> {
    Ok(&self.username)
}
```

So in a way I would actually say borrows being the default nudges you towards using fewer `.clone()`s.

**Comment by youssefhabri** [comment]
Yes, I've been looking at using your `juniper-eager-loading` project :).

Ok, I'll try your suggestion and see how it goes. Thanks.

**Comment by davidpdrsn** [comment]
I think once you remove the clones that you'll find that returning borrows is more common than owned values. So I'll close this issue. Feel free to re-open if you disagree.
