### ISSUE TITLE
Trouble returning a reference from the context

### ISSUE THREAD

**Issue by lucasholder** [davidpdrsn/juniper-from-schema#114]
Sorry I don't think this is really an issue with the library but as I'm a Rust noob I am a bit stuck.

I have a `User` object on my juniper context (loaded with a Rocket request guard) and I'm trying to use it in my QueryFields impl:

```rust
impl QueryFields for Query {
    fn field_me<'a>(
        &'a self,
        executor: &'a juniper::Executor<'_, Context>,
        _trail: &'a QueryTrail<'_, User, juniper_from_schema::Walked>,
    ) -> FieldResult<&'a Option<User>> {
        Ok(&executor.context().user)
    }
}
```

I added the explicit lifetimes because otherwise Rust would complain but now I'm getting this:

```rust
error: `impl` item signature doesn't match `trait` item signature
  --> src/graphql/schema/query.rs:33:5
   |
33 | /     fn field_me<'a>(
34 | |         &'a self,
35 | |         executor: &'a juniper::Executor<'_, Context>,
36 | |         _trail: &'a QueryTrail<'_, User, juniper_from_schema::Walked>,
37 | |     ) -> FieldResult<&'a Option<User>> {
38 | |         Ok(&executor.context().user)
39 | |     }
   | |_____^ found fn(&graphql::schema::query::Query, &juniper::Executor<'_, graphql::context::Context>, &juniper_from_schema::QueryTrail<'_, db::models::user::User, juniper_from_schema::Walked>) -> std::result::Result<&std::option::Option<db::models::user::User>, juniper::FieldError>
```

Is there a way to achieve this?

**Comment by lucasholder** [comment]
I used `@juniper(ownership: "owned")` as a work around but would still be nice to know if it was solvable using references.

**Comment by stijnfrishert** [comment]
@lucasholder, have you found a solution to your problem? Seems to be it's more common send out a copy of you `User`, but as a result I'm adding `@juniper(ownership: "owned")` all over the place.

Maybe @davidpdrsn can help out some Rust beginners? 😇

**Comment by davidpdrsn** [comment]
I'm afraid this isn't possible with the current design. Currently we're optimising to allow you to return data borrowed from the GraphQL type that the field is on (`Query` in the example above).

If we make all lifetimes explicit we get

```rust
impl QueryFields for Query {
    fn field_hello_world<'exec, 'field_ty>(
        &'field_ty self,
        exec: &'exec juniper::Executor<'exec, Context>,
    ) -> juniper::FieldResult<&'field_ty String> {
        let ctx: &'exec Context = exec.context();
        Ok(&ctx.data)
    }
}
```

So currently the lifetime returned is `'field_ty` which is also the lifetime of `self`. That means you can do

```rust
#[derive(Debug)]
struct User {
    name: String,
}

impl UserFields for User {
    fn field_name<'exec, 'field_ty>(
        &'field_ty self,
        exec: &'exec juniper::Executor<'exec, Context>,
    ) -> juniper::FieldResult<&'field_ty String> {
        Ok(&self.name)
    }
}
```

I'm not sure there is a way to make both things possible but I'm open for suggestions. Doesn't have to be PRs. Could also be sample code with new `*Fields` traits that supports both use cases.

I'm afraid you have to return owned data (possibly by cloning):

```graphql
type Query {
  helloWorld: String! @juniper(ownership: "owned")
}
```

```rust
impl QueryFields for Query {
    fn field_hello_world<'exec, 'field_ty>(
        &'field_ty self,
        exec: &'exec juniper::Executor<'exec, Context>,
    ) -> juniper::FieldResult<String> {
        let ctx: &'exec Context = exec.context();
        Ok(ctx.data.clone())
    }
}
```

**Comment by stijnfrishert** [comment]
Thanks for your quick reply, @davidpdrsn, it's helping a lot! I'm still getting my feet wet with GraphQL and Juniper so it's taking me some time to wrap my head around what you're saying.

My context contains a `RefCell`, (my schema supports mutations so I need interior mutability), at which point you essentially _have_ to clone data out (`borrow()` returns a local struct).

Do you mind answering two more beginner questions?
 - Wouldn't it be a better default to have everything return owned, and use an `@juniper` directive to add a reference?
 - Just for my understanding and ease of mind: is it common that these GQL objects aren't directly your data model then, but a layer around it?

**Comment by davidpdrsn** [comment]
> Wouldn't it be a better default to have everything return owned, and use an @juniper directive to add a reference?

Its a tradeoff. My experience is that most fields return borrowed data because they come from some kind of struct with fields for each field in the graphql type. [This](https://github.com/davidpdrsn/graphql-app-example/blob/master/schema.graphql) is the schema for an example app I built.

I think if all your fields return owned data you're incentivised to clone all over and possibly have N+1s query bugs, which isn't ideal.

> Just for my understanding and ease of mind: is it common that these GQL objects aren't directly your data model then, but a lightweight layer around it - aka cheap to copy?

Yes in general I would recommend you keep your GraphQL types and data model types different. They might have things in common but most likely will diverge over time. I normally don't like to conflate view and model code.

**Comment by stijnfrishert** [comment]
Right, that's making more and more sense now! I'll keep that in mind when designing my own GraphQL API :)

Hopefully I didn't hijack the thread too much, looks like the answer to the original question then is to just simply use the `@juniper` directive.

Thanks for indulging me, @davidpdrsn.

**Comment by davidpdrsn** [comment]
No problem. I'll close this issue for now.
