### ISSUE TITLE
Error when using `type` as a parameter in graphql.

### ISSUE THREAD

**Issue by lucasholder** [davidpdrsn/juniper-from-schema#115]
Error when using `type` as a parameter in graphql.

```rust
8 | graphql_schema_from_file!("./src/graphql/schema/schema.graphql");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier, found keyword
```
```graphql
type User {
  accounts(type: String): [Account!]!
}
```

Maybe a bug with the graphql parser?

**Comment by davidpdrsn** [comment]
This was because of an old bug in juniper that didn't allow Rust keywords to be used in the schema. Its since been fixed in juniper and support in juniper-from-schema landed in #122.
