### ISSUE TITLE
Rust type's name changing/prefixing/suffixing?

### ISSUE THREAD

**Issue by stijnfrishert** [davidpdrsn/juniper-from-schema#118]
A lot of the types in my schema have the same names as structures in my model. That means I have double names when using `graphql_schema_from_file!()` to generate these objects, because I'd like to keep my model and my GraphQL "view" seperate.

Sure, the Rust module system makes sure there are no name clashes, but it's awfully inconvenient when tying them together in my mutation fields, having to `use X as ModelX` everything.

Maybe it's an idea to add a `@juniper` directive to change a Rust type's name, or an additional argument to `graphql_schema_from_file!()` to suffix/prefix the type names generated?

**Comment by davidpdrsn** [comment]
Using the module system has worked fine for me in the past but I'm not against adding this feature. PRs are welcome. I will be able to provide help if necessary.

**Comment by davidpdrsn** [comment]
I'm going to close this since its not something I plan to build support for. However PRs are still very welcome 😊
