### ISSUE TITLE
Splitting up implementation across multiple files?

### ISSUE THREAD

**Issue by stijnfrishert** [davidpdrsn/juniper-from-schema#119]
Would it perhaps be possible to support splitting your implementation up across multiple files? The longer your schema is, the longer your .rs that calls `graphql_schema_from_file()`.

I'm not versed enough with Rust to know what that would look like precisely, but seems like a worthy idea? Is this already possible and am I overlooking something?

**Comment by davidpdrsn** [comment]
This is something thats been discussed a few times already. I only think we can support this if juniper gains support for it as well. [That isn't likely](https://github.com/graphql-rust/juniper/issues/743).

The file that calls `graphql_schema_from_file` doesn't need to be huge, you can import all the things it requires. For example you can define `Query` in another file and also implement `QueryFields` there and then import `Query` into the file that calls `graphql_schema_from_file`. That is how I'm handling large schemas.

I'm gonna close this issue for now, but feel to comment if you have more questions. Happy to help 😊

**Comment by stijnfrishert** [comment]
Sure, thanks, that solves the issue for me :)

**Comment by byblakeorriver** [comment]
Is there any way you could show a small example of this? I tried to do what you explained in the above comment and I kept getting an error when trying to implement QueryFields in a file where I wasn't calling `graphql_schema_from_file()`. I am using version 0.5.2 with juniper version 0.14.2. Any help would be greatly appreciated.

**Comment by davidpdrsn** [comment]
@byblakeorriver what was the error? I don't have an example laying around but should just be a matter of importing things from one module into another.
