### ISSUE TITLE
Add support for subscriptions

### ISSUE THREAD

**Issue by caass** [davidpdrsn/juniper-from-schema#120]
From [the docs](https://docs.rs/juniper-from-schema/0.5.2/juniper_from_schema/index.html#graphql-features):

> The goal of this library is to support as much of GraphQL as Juniper does.
>
> [...]
>
> Not supported yet:
>
>  *  Subscriptions (will be supported once Juniper supports subscriptions)
>  *  Type extensions

Juniper has [landed support for subscriptions](https://github.com/graphql-rust/juniper/issues/54#issuecomment-600970533) in master. It would be cool if we could use this library to generate the required boilerplate for subscriptions, especially given the need to write out the code for a [coordinator](https://github.com/graphql-rust/juniper/blob/master/docs/book/content/advanced/subscriptions.md#coordinator).

On first glance, I think this would require a little more code than just copying over the code for mutations and queries. I was going to attack this myself but decided instead to use [`RootNode.as_schema_language()`](https://graphql-rust.github.io/juniper/master/schema/schemas_and_mutations.html#converting-a-rust-schema-to-the-a-hrefhttpsgraphqlorglearnschematype-languagegraphql-schema-languagea) as it already exists and I'm working on a greenfield project 😅

**Comment by davidpdrsn** [comment]
Yes we totally should support subscriptions! Theres a whole bunch of things going on in juniper at the moment actually. I haven't quite had the to time to keep up honestly. I believe they're also removing the sync code and going all in on async. That will most likely also require lots of changes.

I currently don't know when I'll get time to implement it but it will happen at some point.

**Comment by caass** [comment]
Yeah no kidding! I switched from stable to master and like...all of my code broke 🙃 My fault I'm sure, I had a bunch of questionable lifetime stuff going on -- I'm still fairly new to Rust and starting my first project that goes beyond hello world.

Glad to know it's on the radar :)

**Comment by LegNeato** [comment]
FWIW we are leaving the sync code in.

**Comment by davidpdrsn** [comment]
Ah cool. I didn't realize. My plan is to dive back in when async interfaces have landed.

**Comment by davidpdrsn** [comment]
This isn't quite done yet, but progress will be tracked here https://github.com/davidpdrsn/juniper-from-schema/issues/121
