### ISSUE TITLE
Error: unresolved import `juniper`

### ISSUE THREAD

**Issue by iot-resister** [davidpdrsn/juniper-from-schema#131]
Its not clear which dependencies are needed to use this crate. I'm assuming the snippets pasted below would work, but I'm getting this error: 
```
 unresolved import `juniper`
 --> src/main.rs:4:1
````

What I'm running: 

```toml
juniper = "0.14.2"
juniper-from-schema = {git = "https://github.com/davidpdrsn/juniper-from-schema"}
``` 
```rust
use juniper_from_schema::graphql_schema_from_file;

// This is the important line
graphql_schema_from_file!("readme_schema.graphql");

pub struct Context;

impl juniper::Context for Context {}

pub struct Query;

// This trait is generated by `graphql_schema_from_file!` based on the schema
impl QueryFields for Query {
    fn field_hello_world(
        &self,
        _executor: &juniper::Executor<Context>,
        name: String,
    ) -> juniper::FieldResult<String> {
        Ok(format!("Hello, {}!", name))
    }
}

fn main() {
    let ctx = Context;

    let query = "query { helloWorld(name: \"Ferris\") }";

    let (result, errors) = juniper::execute_sync(
        query,
        None,
        &Schema::new(Query, juniper::EmptyMutation::new()),
        &juniper::Variables::new(),
        &ctx,
    )
    .unwrap();

    assert_eq!(errors.len(), 0);
    assert_eq!(
        result
            .as_object_value()
            .unwrap()
            .get_field_value("helloWorld")
            .unwrap()
            .as_scalar_value::<String>()
            .unwrap(),
        "Hello, Ferris!",
    );
}
```
Ideally I'd like support for async/subscriptions but it isn't necessary.

**Comment by davidpdrsn** [comment]
As mentioned in the readme juniper-from-schema master requires the juniper master. The version that's on crates.io requires juniper 0.14. Does it work if you change your juniper reference to be master of their repo?

**Comment by iot-resister** [comment]
I misread that. My apologies.  I got it to run except I added another argument to Schema. I'm assuming its a subscription placeholder?

``&Schema::new(Query, juniper::EmptyMutation::new(), juniper::EmptySubscription::new()),`


Thanks for making such an awesome project!  If you are open to  sponsorship, I'd love to contribute!

**Comment by davidpdrsn** [comment]
I'm not taking sponsorships at the moment. I still have a full time job so while I appreciate the gesture very much I think your money could be better spent donating to people doing full time open source. But thanks anyways 😊
