### ISSUE TITLE
Consider making actix-web example

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/juniper-from-schema#35]
I have made [an example web app using rocket](https://github.com/davidpdrsn/graphql-app-example) and others have also requested an example using actix. I'm not super comfortable doing that since I have never really tried actix.

**Comment by davidpdrsn** [comment]
We might be able to steal from this https://github.com/actix/examples/tree/master/juniper

**Comment by husseinraoouf** [comment]
I have been using actix and juniper for while now i think i could do the example :)

**Comment by davidpdrsn** [comment]
@husseinraoouf That would be great! Let me know when you repo then I'll [include a link to it in the docs](https://docs.rs/juniper-from-schema/0.3.0/juniper_from_schema/#example-web-app)

**Comment by husseinraoouf** [comment]
@davidpdrsn I have finally finished the example, you can take a look at [graphql-actix-example](https://github.com/husseinraoouf/graphql-actix-example)
