### ISSUE TITLE
Should we deny snake_cased fields in your schema?

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/juniper-from-schema#47]
If you define a schema like this

```rust
graphql_schema! {
    schema {
        query: Query
    }

    type Query {
        me: User! @juniper(ownership: "owned")
    }

    type User {
        id: Int!
        app_users: [AppUser!]!
    }

    type AppUser {
        id: Int!
    }
}
```

The field `app_users` on `User` will actually be called `appUsers`. That is because Juniper always converts all field names into camelCase. It doesn't seem like juniper allows you to override that behaviour https://docs.rs/juniper/0.12.0/juniper/macro.graphql_object.html#fields.

I would personally find this a bit confusing or at least surprising. I expect users view their schema as the source of truth, however it actually isn't. Juniper's internal schema is the source truth. Juniper never sees the schema you write.

So to avoid this confusion should it be an error if the schema contains field names in snake_case? Changing this would of course be a breaking change.

What do you think @mastfissh @kiljacken ?

**Comment by kiljacken** [comment]
Depending on how opinionated we'd want the library to be, Introducing at least a warning that you're not following convention would be neat, and maybe an error if we really want to go "one true way". I had no idea the convention was camel case, and I have no real attachment to either casing, but following the broader ecosystem is always nice

**Comment by davidpdrsn** [comment]
I think making it a hard error is best. Camel case does seem to be the convention in GraphQL and since we can’t change what juniper does I think users getting an error is the least confusing thing.

We sorta just have to adopt junipers opinions 🤷‍♂️
