### ISSUE TITLE
`UserType::Real` is deprecated

### ISSUE THREAD

**Issue by davidpdrsn** [davidpdrsn/juniper-from-schema#72]
```
warning: use of deprecated item 'UserType::Real': because reasons
   --> juniper-from-schema/tests/doc_test.rs:118:1
    |
118 | / graphql_schema! {
119 | |     schema {
120 | |         query: Query
121 | |     }
...   |
173 | |     union SearchResult = User
174 | | }
    | | ^ in this macro invocation
    | |_|
    |
```

**Comment by davidpdrsn** [comment]
@theduke Do you have any idea what could be causing this deprecation warning? `rg Real` gives me nothing so I suspect it is coming from a macro somewhere.

**Comment by theduke** [comment]
Well the enum variant is marked as deprecated in the schema, so i guess a Rust deprecated attribute is created somewhere.

ps: cargo-expand is great for debugging macros

**Comment by davidpdrsn** [comment]
Lol yeah that is probably why. Thanks!
