### ISSUE TITLE
Facilitate macros applied to generated Rust enums

### ISSUE THREAD

**Issue by hrbigelow** [davidpdrsn/juniper-from-schema#75]
Currently, there is no way to apply macros to the Rust enums that juniper-from-schema automatically generates from the .graphql file.  It would be very nice to have this feature!

For instance, given a `.graphql` file enum:

```graphql
enum MyEnum {
  RED
  GREEN
  PURPLE
}
```

and, an application requirement:

```rust
// #[macro_use] extern crate diesel;
// extern crate strum;
// #[macro_use] extern crate strum_macros;
 
#[derive(SqlType, QueryId)]
#[postgres(type_name = "my_enum_t")]
pub struct MyEnumST; // this is a Diesel SQL type, analogous to diesel::sql_types::*

#[derive(GraphQLEnum, Debug, IntoStaticStr,
    EnumString, FromSqlRow, AsExpression, Deserialize)]
#[strum(serialize_all = "snake_case")]
#[sql_type = "MyEnumST"]
pub enum MyEnum {
   Red,
   Green,
   Purple
}

// and then, another macro which generates FromSql / ToSql impls:
st_enum_to_gql_enum!(MyEnumST, MyEnum);
```

Could this situation be supported, so that we wouldn't have to define the enum in the Rust code?

**Comment by davidpdrsn** [comment]
I would like to support this if possible 😊 

I think the simplest solution is to support skipping code generation for certain types in the schema. Something like:

```graphql
enum MyEnum @juniper(skip: true) {
    RED
    GREEN
    PURPLE
}

type User @juniper(skip: true) {
    id: ID!
}
```

So if we see an enum or type with `@juniper(skip: true)` we would simply skip generating code for it. Then the user would be able to write exactly the definition necessary.

The big downside here is that you would loose a lot of type safety and your schema and Rust code could easily go out of sync. I think that is a slippery slope and something I want to avoid if at all possible. Maybe the [static-assertions](https://github.com/nvzqz/static-assertions-rs) crate can be used to make sure the user defined types still match the schema.

**Comment by davidpdrsn** [comment]
I have been thinking about this one and I actually don't think the approach I mentioned above is a good idea. It is most likely going to lead to surprises at runtime.

I think a better approach is to have two separate versions of `MyEnum`. One for the database and one for the graphql schema. You can then use `From` to convert between them. Something like this:

```rust
mod models {
    #[derive(SqlType, QueryId)]
    #[postgres(type_name = "my_enum_t")]
    pub struct MyEnumST;

    #[derive(
        GraphQLEnum,
        Debug,
        IntoStaticStr,
        EnumString,
        FromSqlRow,
        AsExpression,
        Deserialize,
    )]
    #[strum(serialize_all = "snake_case")]
    #[sql_type = "MyEnumST"]
    pub enum MyEnum {
        Red,
        Blue,
    }

    st_enum_to_gql_enum!(MyEnumST, MyEnum);
    
    impl From<super::graphql_schema::MyEnum> for MyEnum {
        fn from(x: super::graphql_schema::MyEnum) -> MyEnum {
            match x {
                super::graphql_schema::MyEnum::Blue => MyEnum::Blue,
                super::graphql_schema::MyEnum::Red => MyEnum::Red,
            }
        }
    }
}

mod graphql_schema {
    // this code is generated by the `graphql_schema_from_file!`
    pub enum MyEnum {
        Red,
        Blue
    }

    impl From<super::models::MyEnum> for MyEnum {
        fn from(x: super::models::MyEnum) -> MyEnum {
            match x {
                super::models::MyEnum::Blue => MyEnum::Blue,
                super::models::MyEnum::Red => MyEnum::Red,
            }
        }
    }
}
```

I realise this isn't the most elegant thing because you have to keep the two enums in sync. However the compiler will tell you if you update with `models::MyEnum` without updating the other. The upside is that you have full control over the model enum and can do whatever you want with it.

@hrbigelow What do you think about this approach?

**Comment by mastfissh** [comment]
I like that this mirrors the way that most other structs work. In practice, as long as the compiler makes sure you keep them in sync, I think it won't add much overhead.

**Comment by davidpdrsn** [comment]
Great. I'm gonna close this then. Feel free to re-open in case something else pops up.

**Comment by davidpdrsn** [comment]
Whoops I was a bit too quick there. Gonna give @hrbigelow a chance to respond as well.

**Comment by hrbigelow** [comment]
Hi @davidpdrsn ,

Apologies for my lagging on this.  Full disclosure, my circumstances have changed and I'm no longer working on the project which this was relevant.  But I looked it over and it looks like a decent solution!  The key thing of course is the compile time check, so I think that works.

Thanks again for your work on this!  I hope it is a useful extension to others, and I will store it away in case I come across a Rust/GraphQL application in the future.

Cheers,

Henry

**Comment by lucasholder** [comment]
I'm also facing this problem and was hoping for a better solution :( I'm still a noob so forgive if I'm misunderstanding something. It seems the proposed work around works reasonably well for single enum types but when the types are contained in another type, you have to write all the boilerplate code for that type as well and so on until all your generated structs and boilerplate `From<>` code have to be written by hand. For example:

```gql
enum UserRoleEnum { Admin, Moderator }
type User { user: UserInput! }
type UserInput {
  role: UserRoleEnum!
}
```

If you wanted to `#[derive(SqlType)]` on `UserRoleEnum` you would either have to write the boilerplate code for `UserRoleEnum` but also for `UserInput` and so on. I'm not sure I have a solution to propose but it feels like there has to be a better way.

**Comment by davidpdrsn** [comment]
Yep that kind of macro is exactly what I’ve been doing as well. I actually also think that is better design overall. I’m generally a fan of separating your database and graphql layers.
