### ISSUE TITLE
Output to file (instead of inline)

### ISSUE THREAD

**Issue by bodymindarts** [davidpdrsn/juniper-from-schema#86]
Thanks a lot for this work!

I'd like to output the generated code to a file that I can bring under source control and then `include!(..)` the content of that file. It would require a few changes to this project. Would there be interest in merging a PR with this functionality, or should I just keep it in a fork?

**Comment by davidpdrsn** [comment]
I think its an interesting idea that I hadn't thought of.

Can you elaborate on what the benefits of that approach is? Since there is a 1-to-1 mapping from GraphQL schema to Rust code, wouldn't it be enough to commit the schema?

**Comment by bodymindarts** [comment]
Yes I committing the schema is enough but right now this has manual effort (copying it from the compile output). Also juniper-from-schema has a lot of deps that increase the compile time even though we only need these deps at build time.

What I would like to do is create the schema in `build.rs` and commit it to source code. Then there is not manual effort to check what code was generated and you reduce the runtime deps.
This is also how the protobuf library (prost)[https://github.com/danburkert/prost] works.

**Comment by davidpdrsn** [comment]
Alright. I think it makes sense to implement this in a fork at first and re-evaluate once that is done.

Let me know when you have something that works. I'd love to take a look.

**Comment by davidpdrsn** [comment]
I'm going to close this since it isn't actionable. Feel free to reopen when you have something 😊
