### ISSUE TITLE
Parse error when escape caracter with "r#"

### ISSUE THREAD

**Issue by jiemme2** [davidpdrsn/juniper-from-schema#92]
I have a field name "type", 
so i have to escape it with "r#"  but i obtain a compilation parse error
```
type Block {
  ...
  r#type: String!
  ...
}
```

**Comment by davidpdrsn** [comment]
The parse error is mostly likely from [the GraphQL parser we use](https://crates.io/crates/graphql-parser). I don’t suppose `r#type` is valid GraphQL syntax. Are you able to post the exact error message you get just to make sure?

You’re right that having fields with the same names as Rust keywords doesn’t work. I guess calling the field `type_` on the Rust side would be fine. We should probably handle all [Rust keywords](https://doc.rust-lang.org/reference/keywords.html#strict-keywords) in this way.

**Comment by jiemme2** [comment]
the complete schema that i want to implement is here
https://git.duniter.org/nodes/common/doc/blob/graphql_api_rfc/appendices/0003_RFC/schema.graphqls

with the following schema file content
```
type Block {
  type: String!
}
```
=> i get this compilation error 
```
error: expected identifier, found keyword `type`
 --> lib/modules/gva/src/schema.rs:7:1
  |
7 | graphql_schema_from_file!("lib/modules/gva/resources/schema.gql");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected identifier, found keyword
help: you can escape reserved keywords to use them as identifiers
  |
7 | r#type
  |
```

and with the following content 
```
type Block {
  r#type: String!
}
```
i get this compilation error
```
error: proc macro panicked
 --> lib/modules/gva/src/schema.rs:7:1
  |
7 | graphql_schema_from_file!("lib/modules/gva/resources/schema.gql");
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: schema parse error: Parse error at 21:1
          Unexpected `}[Punctuator]`
          Expected `:`
```
the whole line is escaped

**Comment by davidpdrsn** [comment]
Thanks for the detailed report. I’ll look into it. Shouldn’t be that hard to fix.

Until it’s fixed you’ll have to rename the field I’m afraid.

**Comment by jiemme2** [comment]
Ok.
thank you so much for all this work and quick reply

**Comment by davidpdrsn** [comment]
This landed in https://github.com/davidpdrsn/juniper-from-schema/pull/122.
