### ISSUE TITLE
Input types are generated with private fields

### ISSUE THREAD

**Issue by MathiasKoch** [davidpdrsn/juniper-from-schema#97]
Hi.

It seems like my input types are being generated with private fields, despite the docs stating `Input objects will be converted into Rust structs with public fields.`

In my case, this schema:
```
input CloudFilter {
  name: String!
  accountId: String!
}
```

Generates:
```
pub struct CloudFilter
{
    # [allow (missing_docs)] 
    name : String, 
    # [allow (missing_docs)]
    account_id : String
} 
```

**Comment by davidpdrsn** [comment]
Thanks for noticing! I'll ship a patch release today with the fix.

**Comment by MathiasKoch** [comment]
Thank you!

**Comment by davidpdrsn** [comment]
Version [0.5.1](https://crates.io/crates/juniper-from-schema) is shipped.
